version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always 
    ports:
      - 8002:80
    environment:
      PMA_HOST: db  # Nom du service MySQL dans Docker Compose
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  .dbdata: