version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 manage.py runserver 0.0.0.0:8081'
    ports:
      - 8081:8081
    volumes:
      - .:/app
